# Generated by Django 5.1.1 on 2024-12-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0004_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
